### ISSUE TITLE
프로필 업데이트 시 이미지 경로 잘못 업데이트 되는 현상

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/chainity-api#38]
프로필 업데이트 시 이미지 경로 path도 같이 저장되는 현상

* 임시 방편으로 처리한 코드가 master에만 반영이 되어있음
> https://github.com/JAVACAFE-STUDY/chainity-api/pull/34

**Comment by clghks** [comment]
- master 에 있는 코드 revert 요청 
- 미존재 계정으로 로그인시 에러 발생 오류 수정과 같이 develop에 PR 요청
